# Generated by Django 4.2.16 on 2024-09-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCongratsByName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_by_name_congrats', to='musprivet.category')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musprivet.name')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag')),
            ],
            options={
                'verbose_name': 'поздравление по имени',
                'verbose_name_plural': 'поздравления по имени',
                'db_table': 'service_by_name',
            },
        ),
        migrations.CreateModel(
            name='ServiceCongratsByTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_by_tag_congrats', to='musprivet.category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag')),
            ],
            options={
                'verbose_name': 'поздравление по тегу',
                'verbose_name_plural': 'поздравления по тегу',
                'db_table': 'service_by_tag',
            },
        ),
        migrations.DeleteModel(
            name='ServiceCongrats',
        ),
    ]
