# Generated by Django 4.2.16 on 2024-09-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0002_servicecongratsbyname_servicecongratsbytag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecongratsbyname',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecongratsbyname',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicecongratsbyname',
            name='tag',
        ),
        migrations.CreateModel(
            name='PoemByName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.name')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag')),
            ],
            options={
                'verbose_name': 'стих по имени',
                'verbose_name_plural': 'стихи по именам',
                'db_table': 'poem_by_name',
            },
        ),
        migrations.AddField(
            model_name='servicecongratsbyname',
            name='poem',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='musprivet.poembyname'),
        ),
    ]
