# Generated by Django 4.2.16 on 2024-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0005_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentService',
        ),
        migrations.AlterModelOptions(
            name='paymentservice',
            options={'verbose_name': 'оплата услуги', 'verbose_name_plural': 'оплата услуги'},
        ),
        migrations.AlterModelTable(
            name='paymentservice',
            table='PaymentService',
        ),
        migrations.CreateModel(
            name='PaymentServiceByName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('congratulation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.servicecongratsbyname')),
            ],
            options={
                'verbose_name': 'оплата услуги по имени',
                'verbose_name_plural': 'оплата услуги по имени',
                'db_table': 'PaymentServiceByName',
            },
        ),
    ]
