# Generated by Django 4.2.16 on 2024-09-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0007_blog_alter_review_options_review_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesongs',
            options={'verbose_name': 'песня', 'verbose_name_plural': 'песни'},
        ),
        migrations.RemoveField(
            model_name='servicesongs',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='servicesongs',
            name='media_file',
        ),
        migrations.AddField(
            model_name='servicesongs',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='servicesongs',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ServiceSongsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_video_songs', to='musprivet.category')),
            ],
            options={
                'verbose_name': 'видео песня',
                'verbose_name_plural': 'видео песни',
                'db_table': 'video song',
            },
        ),
    ]
