# Generated by Django 4.2.16 on 2024-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0009_songrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadvertisement',
            options={'verbose_name': 'реклама', 'verbose_name_plural': 'реклама'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.RemoveField(
            model_name='serviceadvertisement',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='serviceadvertisement',
            name='media_file',
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.CreateModel(
            name='ServiceVideoAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_video_ad', to='musprivet.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_video_advertisement', to='musprivet.subcategory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag')),
            ],
            options={
                'verbose_name': 'видео реклама',
                'verbose_name_plural': 'видео реклама',
                'db_table': 'video-advertisement',
            },
        ),
    ]
