# Generated by Django 4.2.16 on 2024-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0010_alter_serviceadvertisement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
