# Generated by Django 4.2.16 on 2024-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0012_remove_serviceadvertisement_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceadvertisement',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='tag',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
