# Generated by Django 4.2.16 on 2024-10-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0013_remove_serviceadvertisement_subcategory_tag_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceadvertisement',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ads', to='musprivet.subcategory'),
        ),
    ]
