# Generated by Django 4.2.16 on 2024-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0014_serviceadvertisement_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdClipPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('R', 'Аудиоролик'), ('S', 'Сценарий')], max_length=1)),
                ('timing', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
                'db_table': 'ad_clip_price',
            },
        ),
        migrations.RemoveField(
            model_name='servicevideoadvertisement',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='servicevideoadvertisement',
            name='video_url',
            field=models.URLField(),
        ),
    ]
