# Generated by Django 4.2.16 on 2024-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0016_alter_servicevideoadvertisement_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
