# Generated by Django 4.2.16 on 2024-10-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0017_alter_serviceadclipprice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadclipprice',
            options={'verbose_name': 'цена на рекламный ролик', 'verbose_name_plural': 'цены на рекламный ролик'},
        ),
        migrations.CreateModel(
            name='ServiceAdClipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('timing', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice')),
            ],
            options={
                'verbose_name': 'заявка на рекламный ролик',
                'verbose_name_plural': 'заявки на рекламные ролики',
                'db_table': 'clip request',
            },
        ),
    ]
