# Generated by Django 4.2.16 on 2024-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0018_alter_serviceadclipprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='city'),
        ),
    ]
