# Generated by Django 4.2.16 on 2024-10-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0019_alter_review_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadclipprice',
            options={'verbose_name': 'цена', 'verbose_name_plural': 'цены'},
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='type',
            field=models.CharField(choices=[('R', 'Аудиоролик'), ('S', 'Сценарий'), ('M', 'Музыка')], max_length=1),
        ),
        migrations.CreateModel(
            name='ServiceAdMusicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice')),
            ],
            options={
                'verbose_name': 'заявка на рекламную музыку',
                'verbose_name_plural': 'заявки на рекламную музыку',
                'db_table': 'music request',
            },
        ),
    ]
