# Generated by Django 4.2.16 on 2024-10-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0020_alter_serviceadclipprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name'], 'verbose_name': 'имя', 'verbose_name_plural': 'имена'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AddField(
            model_name='paymentservice',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice'),
        ),
        migrations.AddField(
            model_name='paymentservicebyname',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='type',
            field=models.CharField(choices=[('R', 'Аудиоролик'), ('S', 'Сценарий'), ('M', 'Музыка'), ('C', 'Музыкальное поздравление')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='name',
            table='name',
        ),
    ]
