# Generated by Django 4.2.16 on 2024-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0021_alter_category_options_alter_name_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentservice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
