# Generated by Django 4.2.16 on 2024-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0022_alter_paymentservice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
