# Generated by Django 4.2.16 on 2024-10-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0024_category_image_tag_image_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'статья блога', 'verbose_name_plural': 'Таблица блога'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Таблица категорий'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name'], 'verbose_name': 'имя', 'verbose_name_plural': 'Таблица имен'},
        ),
        migrations.AlterModelOptions(
            name='poembyname',
            options={'verbose_name': 'стих по имени', 'verbose_name_plural': 'Таблица стихов по именам'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Таблица отзывов'},
        ),
        migrations.AlterModelOptions(
            name='serviceadclipprice',
            options={'verbose_name': 'цена', 'verbose_name_plural': 'Таблица на услуги аудиорекламы'},
        ),
        migrations.AlterModelOptions(
            name='serviceadvertisement',
            options={'verbose_name': 'реклама', 'verbose_name_plural': 'Таблица аудиорекламы'},
        ),
        migrations.AlterModelOptions(
            name='servicecongratsbyname',
            options={'verbose_name': 'поздравление по имени', 'verbose_name_plural': 'Таблица поздравлений по именам'},
        ),
        migrations.AlterModelOptions(
            name='servicecongratsbytag',
            options={'verbose_name': 'поздравление по тегу', 'verbose_name_plural': 'Таблица поздравлений по тегу'},
        ),
        migrations.AlterModelOptions(
            name='servicesongs',
            options={'verbose_name': 'песня', 'verbose_name_plural': 'Таблица песен'},
        ),
        migrations.AlterModelOptions(
            name='servicesongsvideo',
            options={'verbose_name': 'видео песня', 'verbose_name_plural': 'Таблица песен в формате видео'},
        ),
        migrations.AlterModelOptions(
            name='servicevideoadvertisement',
            options={'verbose_name': 'видео реклама', 'verbose_name_plural': 'Таблица аудиорекламы в формате видео'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегория', 'verbose_name_plural': 'Таблица подкатегорий'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Таблица тегов'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='картинка (опционально)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, verbose_name='слаг (автоматически)'),
        ),
        migrations.AlterField(
            model_name='name',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='name',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг (автоматически)'),
        ),
        migrations.AlterField(
            model_name='poembyname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.name', verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='poembyname',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='poembyname',
            name='text',
            field=models.TextField(verbose_name='текст стихотворения'),
        ),
        migrations.AlterField(
            model_name='poembyname',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=None, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='musprivet.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание (каждый пункт с новой строки)'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='price',
            field=models.CharField(max_length=255, verbose_name='цена (целое число)'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='timing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='хронометраж (опционально)'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='serviceadclipprice',
            name='type',
            field=models.CharField(choices=[('R', 'Аудиоролик'), ('S', 'Сценарий'), ('M', 'Музыка'), ('C', 'Музыкальное поздравление')], max_length=1, verbose_name='выберите тип'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ads', to='musprivet.subcategory', verbose_name='подкатегория'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='serviceadvertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbyname',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbyname',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_by_name_congrats', to='musprivet.category', verbose_name='категория (музыкальное поздравление)'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbyname',
            name='poem',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='musprivet.poembyname', verbose_name='стихотворение'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbyname',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_by_tag_congrats', to='musprivet.category', verbose_name='категория (музыкальное поздравление)'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='текст поздравления (опционально)'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг (автоматически)'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='servicecongratsbytag',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_songs', to='musprivet.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='название (опционально)'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicesongsvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_video_songs', to='musprivet.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='servicesongsvideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='название (опционально)'),
        ),
        migrations.AlterField(
            model_name='servicesongsvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicesongsvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='servicevideoadvertisement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание (опционально)'),
        ),
        migrations.AlterField(
            model_name='servicevideoadvertisement',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='servicevideoadvertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='servicevideoadvertisement',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='musprivet.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='слаг (автоматически)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='musprivet.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_female_name_related',
            field=models.BooleanField(default=False, verbose_name='привязан ли к тегу список женских имен'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_male_name_related',
            field=models.BooleanField(default=False, verbose_name='привязан ли к тегу список мужских имен'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер (для тегов Аудиорекламы, номер означает каким по счету тег будет на странице)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг (автоматически)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='musprivet.subcategory', verbose_name='подкатегория (если есть)'),
        ),
    ]
