# Generated by Django 4.2.16 on 2024-10-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0025_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'статья блога', 'verbose_name_plural': '3. Таблица блога'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': '1.1. Таблица категорий'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name'], 'verbose_name': 'имя', 'verbose_name_plural': '2.2. Таблица имен'},
        ),
        migrations.AlterModelOptions(
            name='paymentservice',
            options={'verbose_name': 'оплата услуги', 'verbose_name_plural': 'Форма оплаты услуги музыкального поздравления по тегу'},
        ),
        migrations.AlterModelOptions(
            name='paymentservicebyname',
            options={'verbose_name': 'оплата услуги по имени', 'verbose_name_plural': 'Форма оплаты услуги музыкального поздравления по имени'},
        ),
        migrations.AlterModelOptions(
            name='poembyname',
            options={'verbose_name': 'стих по имени', 'verbose_name_plural': '2.4. Таблица стихов по именам'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': '4. Таблица отзывов'},
        ),
        migrations.AlterModelOptions(
            name='serviceadclipprice',
            options={'verbose_name': 'цена', 'verbose_name_plural': '7. Таблица цен на услуги аудиорекламы и поздравлений'},
        ),
        migrations.AlterModelOptions(
            name='serviceadcliprequest',
            options={'verbose_name': 'заявка на рекламный ролик', 'verbose_name_plural': 'Форма заявки на рекламные ролики и сценарии'},
        ),
        migrations.AlterModelOptions(
            name='serviceadmusicrequest',
            options={'verbose_name': 'заявка на рекламную музыку', 'verbose_name_plural': 'Форма заявки на рекламную музыку'},
        ),
        migrations.AlterModelOptions(
            name='serviceadvertisement',
            options={'verbose_name': 'реклама', 'verbose_name_plural': '6.1. Таблица аудиорекламы'},
        ),
        migrations.AlterModelOptions(
            name='servicecongratsbyname',
            options={'verbose_name': 'поздравление по имени', 'verbose_name_plural': '2.5. Таблица поздравлений по именам'},
        ),
        migrations.AlterModelOptions(
            name='servicecongratsbytag',
            options={'verbose_name': 'поздравление по тегу', 'verbose_name_plural': '2.3. Таблица поздравлений по тегу'},
        ),
        migrations.AlterModelOptions(
            name='servicesongs',
            options={'verbose_name': 'песня', 'verbose_name_plural': '5.1. Таблица песен'},
        ),
        migrations.AlterModelOptions(
            name='servicesongsvideo',
            options={'verbose_name': 'видео песня', 'verbose_name_plural': '5.2. Таблица песен в формате видео'},
        ),
        migrations.AlterModelOptions(
            name='servicevideoadvertisement',
            options={'verbose_name': 'видео реклама', 'verbose_name_plural': '6.2. Таблица аудиорекламы в формате видео'},
        ),
        migrations.AlterModelOptions(
            name='songrequest',
            options={'verbose_name': 'заявка на песню', 'verbose_name_plural': 'Форма заявки на песню'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегория', 'verbose_name_plural': '1.2. Таблица подкатегорий'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': '2.1. Таблица тегов'},
        ),
        migrations.AddField(
            model_name='servicesongsvideo',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'вертикальный'), ('H', 'горизонтальный')], max_length=1, null=True, verbose_name='выберите тип видео'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='congratulation',
            field=models.TextField(blank=True, null=True, verbose_name='текст поздравления'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.servicecongratsbytag', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='congratulation',
            field=models.TextField(blank=True, null=True, verbose_name='текст поздравления'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='paymentservicebyname',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.servicecongratsbyname', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='serviceadcliprequest',
            name='timing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='хронометраж'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='аудио файл'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='serviceadmusicrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musprivet.serviceadclipprice', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='servicesongs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание (опционально)'),
        ),
        migrations.AlterField(
            model_name='servicesongsvideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание (опционально)'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
    ]
