# Generated by Django 4.2.16 on 2024-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musprivet', '0027_remove_servicesongsvideo_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesongsvideo',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='servicevideoadvertisement',
            name='video_file',
        ),
        migrations.AddField(
            model_name='servicesongsvideo',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='обложка'),
        ),
        migrations.AddField(
            model_name='servicesongsvideo',
            name='video_mp4',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='видео mp4'),
        ),
        migrations.AddField(
            model_name='servicesongsvideo',
            name='video_webm',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='видео webM'),
        ),
        migrations.AddField(
            model_name='servicevideoadvertisement',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='обложка'),
        ),
        migrations.AddField(
            model_name='servicevideoadvertisement',
            name='video_mp4',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='видео mp4'),
        ),
        migrations.AddField(
            model_name='servicevideoadvertisement',
            name='video_webm',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='видео webM'),
        ),
    ]
